import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const base = process.env.JOBFLY_URL || 'http://127.0.0.1:8787';
const out = process.env.JOBFLY_VERIFY_DIR || '/mnt/donto-data/donto-resources/research/fly-jsonresume-20260912/light-verification';
await fs.mkdir(out,{recursive:true});
const browser = await chromium.launch({executablePath:process.env.CHROME_PATH || '/home/ajax/.agent-browser/browsers/chrome-150.0.7871.24/chrome',args:['--no-sandbox','--enable-unsafe-swiftshader','--use-angle=swiftshader-webgl']});
const context = await browser.newContext({viewport:{width:1440,height:1000}});
const page = await context.newPage(); const errors=[];
page.on('pageerror',e=>errors.push(e.message));
let id;
const read=()=>page.evaluate(id=>fetch(`/api/state?session=${id}`).then(r=>r.json()),id);
async function until(fn,seconds=150){const end=Date.now()+seconds*1000;while(Date.now()<end){const s=await read();if(fn(s))return s;await page.waitForTimeout(900);}throw Error('Simulation timed out');}
try {
 await page.goto(base); await page.getByRole('heading',{name:'Start with your resume.'}).waitFor();
 assert.equal(await page.locator('canvas').count(),0);
 await page.screenshot({path:`${out}/onboarding-desktop.png`,fullPage:true});
 await page.setViewportSize({width:390,height:844});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.screenshot({path:`${out}/onboarding-mobile.png`,fullPage:true});
 await page.setViewportSize({width:1440,height:1000});
 await page.getByRole('button',{name:/Use thomasdavis resume/}).click();
 await page.getByRole('heading',{name:'Looks like you?'}).waitFor({timeout:45000});
 const resume=JSON.parse(await page.locator('#resume-json').inputValue());assert.equal(resume.basics.name,'Thomas Davis');
 const download=page.waitForEvent('download');await page.getByLabel('Download resume.json',{exact:true}).click();assert.equal((await download).suggestedFilename(),'resume.json');
 await page.getByRole('button',{name:'Find my jobs',exact:true}).click();
 await page.waitForURL(/\/s\/[a-f0-9]{48}$/, {timeout:120000});
 id=new URL(page.url()).pathname.split('/').pop();
 const state=await until(s=>s.status==='ready');assert.equal(state.updates,0);
 const jobs=await page.evaluate(id=>fetch(`/api/jobs?session=${id}`).then(r=>r.json()),id);
 assert(jobs.jobs.length>0);assert(jobs.jobs.every(j=>j.source!=='example' && /^https:\/\//.test(j.url)));
 await page.getByRole('button',{name:'Start',exact:true}).click();
 const landed=await until(s=>s.landed);assert(landed.totalSpikes>0);
 await page.getByLabel('Optional feedback reason').fill('Verification: preference saved to this session.');
 const changedResponse=page.waitForResponse(r=>r.url().includes('/api/feedback')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'I like this',exact:true}).click();
 const feedback=await(await changedResponse).json();assert(feedback.changed>0);
 const learned=await until(s=>s.updates===1);assert(learned.preferences[landed.landed]>0);
 await page.getByRole('button',{name:'Pause',exact:true}).click();await until(s=>!s.running);
 await page.waitForTimeout(1500);await page.screenshot({path:`${out}/session-desktop.png`,fullPage:true});
 await page.getByRole('button',{name:'Brain',exact:true}).click();await page.waitForTimeout(1000);await page.screenshot({path:`${out}/brain-desktop.png`,fullPage:true});
 await page.getByRole('button',{name:'Explore',exact:true}).click();await page.setViewportSize({width:390,height:844});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`${out}/session-mobile.png`,fullPage:true});
 const reopened=await browser.newContext();const second=await reopened.newPage();await second.goto(`${base}/s/${id}`);
 await second.waitForFunction(()=>document.body.innerText.includes('1 ratings'),undefined,{timeout:120000});
 const saved=await second.evaluate(id=>fetch(`/api/resume.json?session=${id}`).then(r=>r.json()),id);assert.equal(saved.basics.name,'Thomas Davis');
 await reopened.close();
 await fs.writeFile(`${out}/private-session.json`,JSON.stringify({id}),{mode:0o600});
 await fs.writeFile(`${out}/results.json`,JSON.stringify({jobCount:jobs.jobs.length,source:jobs.source,landed:landed.landed,changedEdges:feedback.changed,preference:learned.preferences[landed.landed],reopened:'passed',mobile:'passed',errors},null,2));
 assert.deepEqual(errors,[]);console.log(JSON.stringify({jobCount:jobs.jobs.length,source:jobs.source,changedEdges:feedback.changed,reopened:true,errors}));
} finally { await browser.close(); }
